Adding new MF-MF causal relations
geneontology/go-shapes pull request #281
Opened 2022-10-24 12:50 UTC by vanaukenk

Note that these relations have been added to RO, but there isn't yet an official RO release including them (latest RO release is 2022-09-07).

2022-10-28 20:35 UTC, vanaukenk commented
I think we're still waiting on a new build of go-lego-reacto in order to validate the new relations.  It looks like the last successful snapshot was 2022-10-24?
If so, that would explain the continued failure, as the RO was released on 2022-10-26.

2022-11-02 18:52 UTC, vanaukenk commented
2022-10-28 snapshot contains the new RO relations in go-lego-reacto.
Still not certain why the Travis checks are failing.

2022-11-02 18:54 UTC, balhoff commented
@vanaukenk the tests were broken, but I fixed them. I merged the master branch into this one to make them run.

2022-11-02 18:58 UTC, vanaukenk commented
Thank you so much @balhoff !

2022-11-03 14:21 UTC, balhoff requested changes

2022-11-03 14:21 UTC, balhoff commented on shapes/go-cam-shapes.shex
> +PREFIX removes_input_for: http://purl.obolibrary.org/obo/RO_0012010
@vanaukenk I figured it out — you need angle brackets around these IRIs. :-)

2022-11-03 14:24 UTC, vanaukenk commented
Ugh.  Thanks @balhoff

2022-11-03 14:48 UTC, merged